version: '3.8'
services:
  postgres:
    container_name: trn_inventory_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ./postgres/
    ports:
      - '5432:5432'
    volumes:
      - 'pg-data:/var/lib/postgresql'
volumes:
  pg-data: null